# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-27 07:02
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tons', models.FloatField()),
                ('freight', models.IntegerField()),
                ('advance', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('hamali', models.IntegerField()),
                ('netcollection', models.IntegerField()),
                ('collection_date', models.DateField()),
                ('paid_date', models.DateField()),
                ('paid_balance', models.IntegerField()),
                ('station', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerConsigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Customer name', max_length=40)),
                ('contact', models.CharField(help_text='contact', max_length=40)),
                ('address', models.CharField(help_text='address', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCosignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Customer name', max_length=40)),
                ('contact', models.CharField(help_text='Contact', max_length=40)),
                ('address', models.CharField(help_text='address', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lorry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_no', models.CharField(help_text='truck No', max_length=50)),
                ('driver_name', models.CharField(help_text='Driver name', max_length=30)),
                ('driver_id', models.CharField(help_text='Driver ID', max_length=50)),
                ('driver_contact', models.CharField(help_text='Contact', max_length=50)),
                ('owner_name', models.CharField(help_text='Owner name', max_length=50)),
                ('owner_contact', models.CharField(help_text='Owner Contact', max_length=50)),
                ('licence_id', models.CharField(help_text='licence_id', max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='accountentry',
            name='customer_consignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.CustomerCosignee'),
        ),
        migrations.AddField(
            model_name='accountentry',
            name='customer_consigner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.CustomerConsigner'),
        ),
        migrations.AddField(
            model_name='accountentry',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Lorry'),
        ),
    ]
