# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-14 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_profile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorry',
            name='driver_id',
            field=models.CharField(blank=True, help_text='Driver ID', max_length=50, null=True),
        ),
    ]
