# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-08 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20190807_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentry',
            name='advance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='freight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='hamali',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='netcollection',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='paid_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='tons',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
