# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-09 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20190808_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentry',
            name='advance',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='balance',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='freight',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='hamali',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='netcollection',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='paid_balance',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='tons',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
    ]
