# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-11 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20190809_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorry',
            name='commission_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
