# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-30 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_lorry_commission_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountentry',
            name='driver_paid_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
